import { useEffect, useMemo, useState } from "react";
import { Link, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { CalendarDays, ChevronRight, CircleDollarSign, Compass, LayoutDashboard, MapPin, Plus, Search, Sparkles, Trash2 } from "lucide-react";
import { api } from "../Services/api";

const fmt = (date) => date ? new Intl.DateTimeFormat("en-IN", { month: "short", day: "numeric", year: "numeric" }).format(new Date(date)) : "Dates to be decided";
const money = (amount) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(amount || 0));

function Layout({ children }) {
  const nav = [
    ["dashboard", "Overview", LayoutDashboard], ["trips", "My trips", Compass], ["create", "Plan a trip", Plus],
    ["cities", "Discover cities", MapPin], ["activities", "Find activities", Sparkles],
  ];
  return <div className="travel-shell"><aside className="side-nav"><Link className="brand" to="/app/dashboard"><Compass /> <span>Globe<span>Trotter</span></span></Link><p className="nav-label">Travel planner</p>{nav.map(([path, label, Icon]) => <Link key={path} className="nav-link" to={`/app/${path}`}><Icon size={18}/>{label}</Link>)}<div className="nav-bottom"><p>Ready for your next story?</p><Link to="/app/create" className="nav-cta"><Plus size={16}/> New trip</Link></div></aside><main className="travel-main">{children}</main></div>;
}

function useTrips() {
  const [trips, setTrips] = useState([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const reload = async () => { setLoading(true); try { setTrips((await api("/trips")).trips); setError(""); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { reload(); }, []); return { trips, error, loading, reload };
}
function useDashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { api("/dashboard").then(setData).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  return { data, error, loading };
}

function PageTitle({ eyebrow, title, copy, action }) { return <div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{copy && <p className="subcopy">{copy}</p>}</div>{action}</div>; }
function Notice({ children }) { return <div className="notice">{children}</div>; }

function Dashboard() {
  const { data, error, loading } = useDashboard(); const user = JSON.parse(localStorage.getItem("globetrotter_user") || "{}"); const cities = data?.recommendedCities || [];
  return <Layout><PageTitle eyebrow="Your travel studio" title={`Where will you go${user.name ? `, ${user.name.split(" ")[0]}` : ""}?`} copy="Plan the details, then let the journey do the rest." action={<Link className="button" to="/app/create"><Plus size={18}/> Plan a new trip</Link>}/>{error && <Notice>{error}</Notice>}<section className="hero-card"><div><p className="eyebrow light">Make space for wonder</p><h2>Turn a map full of pins into a trip worth remembering.</h2><Link to="/app/create" className="button pale">Start planning <ChevronRight size={17}/></Link></div></section><div className="dashboard-stats"><div><p>Upcoming trips</p><b>{data?.upcomingTrips?.length || 0}</b></div><div><p>Planned budget</p><b>{money(data?.budgetHighlights?.plannedBudget)}</b></div><div><p>Recently edited</p><b>{data?.recentTrips?.length || 0}</b></div></div><section className="section-head"><h2>Recent journeys</h2><Link to="/app/trips">View all</Link></section>{loading ? <p className="muted">Loading your trips…</p> : <div className="trip-grid">{data?.recentTrips?.length ? data.recentTrips.slice(0, 3).map(trip => <TripCard key={trip.id} trip={trip}/>) : <EmptyTrips/>}</div>}<section className="section-head"><h2>Travel inspiration</h2><Link to="/app/cities">Explore cities</Link></section><div className="city-grid">{cities.map(city => <CityCard key={city.id} city={city}/>)}</div></Layout>;
}
function TripCard({ trip }) { return <Link className="trip-card" to={`/app/builder/${trip.id}`}><div className="trip-image" style={trip.coverImage ? { backgroundImage: `linear-gradient(0deg, rgba(13,30,39,.76), transparent), url(${trip.coverImage})` } : undefined}><span>{trip._count?.stops ?? trip.stops?.length ?? 0} destinations</span><h3>{trip.name}</h3></div><div className="trip-card-info"><CalendarDays size={16}/><span>{fmt(trip.startDate)} - {fmt(trip.endDate)}</span><ChevronRight size={17}/></div></Link>; }
function EmptyTrips() { return <div className="empty-card"><Compass size={28}/><h3>Your next trip starts here</h3><p>Give an idea dates and a name; we’ll help shape the itinerary.</p><Link className="text-link" to="/app/create">Plan your first trip</Link></div>; }
function CityCard({ city, action }) { return <article className="city-card"><div className="city-photo" style={city.imageUrl ? {backgroundImage:`linear-gradient(0deg,rgba(12,25,30,.55),transparent),url(${city.imageUrl})`} : undefined}/><div className="city-card-copy"><p>{city.country}</p><h3>{city.name}</h3>{action}</div></article>; }

function CreateTrip() {
  const navigate = useNavigate(); const [form, setForm] = useState({ name:"", startDate:"", endDate:"", description:"", budget:"", coverImage:"" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async e => { e.preventDefault(); setBusy(true); setError(""); try { const { trip } = await api("/trips", { method:"POST", body:JSON.stringify({...form, budget: form.budget || null, coverImage: form.coverImage || null}) }); navigate(`/app/builder/${trip.id}`); } catch(e) { setError(e.message); } finally { setBusy(false); } };
  return <Layout><PageTitle eyebrow="Step 1 of 3" title="Start with the feeling." copy="Name your trip and give it a window of time. You can refine everything else later."/><div className="planner-split"><form className="form-card" onSubmit={submit}>{error && <Notice>{error}</Notice>}<label>Trip name<input required placeholder="e.g. Rajasthan heritage trail" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="two-col"><label>Start date<input required type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>End date<input required type="date" min={form.startDate} value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></label></div><label>Trip budget <span>optional, in INR</span><input type="number" min="0" placeholder="e.g. 25000" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></label><label>Cover image URL <span>optional</span><input type="url" placeholder="https://…" value={form.coverImage} onChange={e=>setForm({...form,coverImage:e.target.value})}/></label><label>What do you imagine?<textarea placeholder="Food, heritage, mountains, a little spontaneity…" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="button" disabled={busy}>{busy ? "Creating…" : "Create and build itinerary"}<ChevronRight size={18}/></button></form><aside className="tip-card"><Sparkles/><p className="eyebrow">A thoughtful start</p><h2>Keep the first version simple.</h2><p>Add your cities next, then give each day a few anchors. The best itineraries have room to breathe.</p></aside></div></Layout>;
}

function useTrip(id) { const [trip,setTrip]=useState(null); const [error,setError]=useState(""); const reload=async()=>{try{setTrip((await api(`/trips/${id}`)).trip);setError("");}catch(e){setError(e.message);}}; useEffect(()=>{reload();},[id]);return{trip,error,reload}; }
function Builder() {
  const { id } = useParams(); const { trip,error,reload } = useTrip(id); const [cities,setCities]=useState([]); const [query,setQuery]=useState(""); const [dates,setDates]=useState({arrivalDate:"",departureDate:""}); const [message,setMessage]=useState("");
  const search = async () => { try { setCities((await api(`/cities?search=${encodeURIComponent(query)}`)).cities); } catch(e) { setMessage(e.message); setCities([]); } }; useEffect(()=>{search();},[]);
  const addStop=async city=>{ if(!dates.arrivalDate||!dates.departureDate)return setMessage("Choose arrival and departure dates before adding a city."); try{await api(`/trips/${id}/stops`,{method:"POST",body:JSON.stringify({cityId:city.id,...dates})});setMessage(`${city.name} was added to your route.`);reload();}catch(e){setMessage(e.message);}};
  if (!trip && !error) return <Layout><p className="muted">Loading itinerary builder…</p></Layout>;
  return <Layout><PageTitle eyebrow="Step 2 of 3" title={trip ? trip.name : "Build your itinerary"} copy={trip ? `${fmt(trip.startDate)} - ${fmt(trip.endDate)} · Add places, then fill your days with experiences.` : error} action={<Link className="button outline" to={`/app/itinerary/${id}`}>View itinerary</Link>}/>{message && <Notice>{message}</Notice>}<div className="builder-layout"><section><div className="section-head"><h2>Your route</h2><span className="muted">{trip?.stops?.length || 0} stops</span></div><div className="route-list">{trip?.stops?.length ? trip.stops.map((stop,i)=><article className="route-stop" key={stop.id}><div className="stop-count">{i+1}</div><div><h3>{stop.city.name}, {stop.city.country}</h3><p>{fmt(stop.arrivalDate)} - {fmt(stop.departureDate)}</p></div><Link to={`/app/activities?trip=${id}&stop=${stop.id}&date=${stop.arrivalDate.slice(0,10)}`} className="text-link">Add activities</Link></article>) : <EmptyTrips/>}</div></section><aside className="discovery-panel"><p className="eyebrow">Add a destination</p><div className="search-bar"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Search an Indian city"/><button onClick={search}>Search</button></div><div className="two-col compact"><label>Arrive<input type="date" value={dates.arrivalDate} min={trip?.startDate?.slice(0,10)} max={trip?.endDate?.slice(0,10)} onChange={e=>setDates({...dates,arrivalDate:e.target.value})}/></label><label>Leave<input type="date" value={dates.departureDate} min={dates.arrivalDate || trip?.startDate?.slice(0,10)} max={trip?.endDate?.slice(0,10)} onChange={e=>setDates({...dates,departureDate:e.target.value})}/></label></div><div className="city-results">{cities.map(city=><div className="city-result" key={city.id}><MapPin size={18}/><span><b>{city.name}</b><small>{city.country}</small></span><button className="icon-button" onClick={()=>addStop(city)} title={`Add ${city.name}`}><Plus size={17}/></button></div>)}</div></aside></div></Layout>;
}

function CitySearch() { const [q,setQ]=useState("");const [cities,setCities]=useState([]);const [countries,setCountries]=useState([]);const [country,setCountry]=useState("");const [error,setError]=useState("");const search=async()=>{try{setCities((await api(`/cities?search=${encodeURIComponent(q)}&country=${encodeURIComponent(country)}`)).cities);setError("");}catch(e){setError(e.message);}};useEffect(()=>{api("/discovery/meta").then(data=>setCountries(data.countries)).catch(e=>setError(e.message));},[]);useEffect(()=>{search();},[country]);return <Layout><PageTitle eyebrow="Discover India" title="Find a place that moves you." copy="Search Indian destinations, then add the right one to your route."/>{error&&<Notice>{error}</Notice>}<div className="large-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Try Jaipur, Leh, Kochi…"/><button className="button" onClick={search}>Search</button></div><div className="filter-row"><button className={!country?"filter-chip active":"filter-chip"} onClick={()=>setCountry("")}>All destinations</button>{countries.map(item=><button key={item} className={country===item?"filter-chip active":"filter-chip"} onClick={()=>setCountry(item)}>{item}</button>)}</div><div className="city-grid large">{cities.length?cities.map(city=><CityCard city={city} key={city.id} action={<Link className="text-link" to="/app/create">Plan a trip <ChevronRight size={15}/></Link>}/>):<EmptyCities/>}</div></Layout>; }
function EmptyCities(){return <div className="empty-card"><MapPin size={28}/><h3>No destinations found</h3><p>Try a different search or add cities through the database seed script.</p></div>}

function ActivitySearch() { const nav=useNavigate();const [activities,setActivities]=useState([]);const [q,setQ]=useState("");const [categories,setCategories]=useState([]);const [category,setCategory]=useState("");const [error,setError]=useState("");const { trip,stop,date }=Object.fromEntries(new URLSearchParams(window.location.search)); const search=async()=>{try{const data=await api(`/activities?search=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}`);setActivities(data.activities);setError("");}catch(e){setError(e.message);}};useEffect(()=>{api("/discovery/meta").then(data=>setCategories(data.categories)).catch(e=>setError(e.message));},[]);useEffect(()=>{search();},[category]); const add=async activity=>{if(!trip||!stop)return setError("Open this page from an itinerary stop to add an activity.");try{await api(`/trips/${trip}/stops/${stop}/activities`,{method:"POST",body:JSON.stringify({name:activity.name,activityId:activity.id,scheduledDate:date || new Date().toISOString().slice(0,10),estimatedCost:activity.basePrice||0,durationMinutes:activity.durationMinutes||90})});nav(`/app/builder/${trip}`);}catch(e){setError(e.message);}}; return <Layout><PageTitle eyebrow="Experiences" title="Make every day feel like yours." copy="Search activities by place, passion, or a passing curiosity."/>{error&&<Notice>{error}</Notice>}<div className="filters"><div className="search-bar"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Food, heritage, adventure…"/><button onClick={search}>Search</button></div></div><div className="filter-row"> <button className={!category?"filter-chip active":"filter-chip"} onClick={()=>setCategory("")}>All activities</button>{categories.map(item=><button key={item} className={category===item?"filter-chip active":"filter-chip"} onClick={()=>setCategory(item)}>{item}</button>)}</div><div className="activity-list">{activities.length?activities.map(a=><article key={a.id} className="activity-card"><div className="activity-icon"><Sparkles/></div><div><p>{a.city?.name || "Local experience"}{a.category ? ` · ${a.category}` : ""}</p><h3>{a.name}</h3><p className="muted">{a.description || "An experience worth putting on your map."}</p><div className="activity-meta"><span>{a.durationMinutes || 90} min</span><span>{money(a.basePrice)}</span></div></div><button className="button small" onClick={()=>add(a)}><Plus size={16}/> Add</button></article>):<EmptyActivities search={search}/>}</div></Layout>; }
function EmptyActivities({search}){return <div className="empty-card"><Sparkles size={28}/><h3>What sounds fun?</h3><p>Search the activity library to find experiences stored in your database.</p><button className="text-link" onClick={search}>Browse activities</button></div>}

function Itinerary() { const {id}=useParams();const {trip,error}=useTrip(id);const days=useMemo(()=>{if(!trip)return[];let a=[];let cur=new Date(trip.startDate);const end=new Date(trip.endDate);while(cur<=end){a.push(new Date(cur));cur.setDate(cur.getDate()+1)}return a},[trip]);return <Layout><PageTitle eyebrow="Step 3 of 3" title={trip?.name || "Your itinerary"} copy="A gentle day-by-day view of the moments you’ve chosen." action={<Link to={`/app/budget/${id}`} className="button"><CircleDollarSign size={17}/> Budget</Link>}/>{error&&<Notice>{error}</Notice>}<div className="itinerary">{days.map((day,index)=>{const iso=day.toISOString().slice(0,10);const activeStops=trip.stops?.filter(s=>new Date(s.arrivalDate)<=day&&new Date(s.departureDate)>=day)||[];return <section className="day-card" key={iso}><div className="day-tag"><span>Day {index+1}</span><b>{new Intl.DateTimeFormat("en-IN",{weekday:"short",month:"short",day:"numeric"}).format(day)}</b></div><div className="day-content">{activeStops.length?activeStops.map(stop=><div key={stop.id}><h3><MapPin size={17}/>{stop.city.name}</h3>{stop.plannedActivities?.filter(a=>a.scheduledDate?.slice(0,10)===iso).length?stop.plannedActivities.filter(a=>a.scheduledDate?.slice(0,10)===iso).map(a=><div className="activity-row" key={a.id}><span className="dot"/><div><b>{a.name}</b><small>{a.durationMinutes || 90} min · {money(a.estimatedCost)}</small></div></div>):<p className="muted">An open day - leave room for a happy detour.</p>}</div>):<p className="muted">Travel day. The route is still taking shape.</p>}</div></section>})}</div></Layout>; }

function Budget() { const {id}=useParams();const [data,setData]=useState(null);const [error,setError]=useState("");useEffect(()=>{api(`/trips/${id}/budget`).then(setData).catch(e=>setError(e.message))},[id]);const breakdown=Object.entries(data?.breakdown||{});return <Layout><PageTitle eyebrow="Travel finances" title="Spend with a little more ease." copy="A clear snapshot of your estimated costs, before you step out the door."/>{error&&<Notice>{error}</Notice>}<div className="budget-summary"><section><p>Estimated trip total</p><h2>{money(data?.estimatedTotal)}</h2><span>{data?.budget===null||data?.budget===undefined?"No trip budget set":`${money(data.remaining)} remaining from ${money(data.budget)}`}</span></section><section><p>Average per day</p><h2>{money(data?.averagePerDay)}</h2><span>Based on your current plan</span></section></div><section className="budget-card"><div className="section-head"><h2>Cost breakdown</h2><CircleDollarSign/></div>{breakdown.length?breakdown.map(([name,value])=><div className="cost-row" key={name}><span>{name.replace("_"," ")}</span><div><i style={{width:`${Math.max(8, Number(value)/(data.estimatedTotal||1)*100)}%`}}/></div><b>{money(value)}</b></div>):<EmptyTrips/>}</section></Layout>; }

function Trips() {const {trips,error,loading,reload}=useTrips();const nav=useNavigate();const del=async id=>{if(!confirm("Delete this trip? This cannot be undone."))return;try{await api(`/trips/${id}`,{method:"DELETE"});reload()}catch(e){alert(e.message)}};return <Layout><PageTitle eyebrow="Your library" title="All your journeys." copy="Revisit a plan, tighten up the details, or dream up a new route." action={<Link className="button" to="/app/create"><Plus size={17}/> New trip</Link>}/>{error&&<Notice>{error}</Notice>}{loading?<p className="muted">Loading trips…</p>:<div className="trip-grid all-trips">{trips.length?trips.map(t=><div className="trip-card-wrap" key={t.id}><TripCard trip={t}/><button className="delete-trip" onClick={()=>del(t.id)}><Trash2 size={16}/></button></div>):<EmptyTrips/>}</div>}</Layout>}

export default function TravelApp(){return <Routes><Route path="dashboard" element={<Dashboard/>}/><Route path="create" element={<CreateTrip/>}/><Route path="builder/:id" element={<Builder/>}/><Route path="cities" element={<CitySearch/>}/><Route path="activities" element={<ActivitySearch/>}/><Route path="itinerary/:id" element={<Itinerary/>}/><Route path="budget/:id" element={<Budget/>}/><Route path="trips" element={<Trips/>}/><Route path="*" element={<Navigate to="dashboard" replace/>}/></Routes>}
